#!/bin/bash

RED="\e[31m"

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo -e "${RED}!! run as root !!${ENDCOLOR}"
    exit
fi

cd / 
cd bin
rm automator
wget https://raw.githubusercontent.com/AROA-DEV/automator/Beta-testing/Dedicated/Debian/D-automator # change link when pass to release version ->;
# wget https://raw.githubusercontent.com/AROA-DEV/automator/main/Dedicated/Debian/D-automator
mv D-automator automator
chmod +x automator

echo
echo 
echo